### PR TITLE
Update apt.txt without special characters 

### PR DESCRIPTION
**Pull request by betatim**
Let's see if this fixes it

### CODE REVIEW

**Review by ajstewartlang — APPROVED** [review]

**Comment by betatim** [comment]
This successfully built: https://mybinder.org/v2/gh/betatim/SNCF_TidyTuesday/patch-1?urlpath=rstudio (the link goes straight to RStudio). I haven't tried to run any of the R code though.

**Comment by ajstewartlang** [comment]
*Huge* thanks - this is looking hugely promising - I'm now rebuilding with an extra package for rendering of png images - I'm feeling confident...

**Comment by ajstewartlang** [comment]
Outstanding!  It all works - I'll post a follow up to where this conversation started.  btw I had updated my repo after your fork so just copied in the apt.txt text manually.  Many, many thanks!

**Comment by betatim** [comment]
Goodo! Should we close this PR then?

**Comment by ajstewartlang** [comment]
Thanks - yes, I'll do that now.  Thanks again.

**Pull request closed without merging**
